"""Write demo/atmosphere.js from source/physics/AtmosphereTable.cpp.

    python3 demo/tools/bake_atmosphere.py

The NRLMSIS 2.1 table is data, not code, so it is copied rather than ported:
this reads the C++ rows and writes them out as a JavaScript module, number for
number, in the same text the C++ carries. `check_shaders.py` compares the two
and `tools/verify.sh` runs that, so a rebake of the C++ table
(`tools/bake_atmosphere.py` at the repo root, which needs pymsis) that is not
carried across here fails verify rather than leaving the page on the old sky.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
CPP = os.path.join(REPO, "source", "physics", "AtmosphereTable.cpp")
OUT = os.path.join(REPO, "demo", "atmosphere.js")

ROW = re.compile(r"\{\s*([^,}]+),\s*([^,}]+),\s*([^,}]+),\s*([^,}]+),\s*([^,}]+)\s*\},\s*//\s*(\d+) km")


def parse(source):
    """(rows, bottom, step, quiet, active) out of the C++, as text fields."""
    rows = int(re.search(r"const int kTableRows = (\d+);", source).group(1))
    bottom = re.search(r"const double kTableBottomKm = ([0-9.]+);", source).group(1)
    step = re.search(r"const double kTableStepKm = ([0-9.]+);", source).group(1)
    tables = {}
    for name in ("kTableQuiet", "kTableActive"):
        start = source.index(f"const Row {name}[] = {{") + len(f"const Row {name}[] = {{")
        end = source.index("};", start)
        tables[name] = [m.groups() for m in ROW.finditer(source[start:end])]
    return rows, bottom, step, tables["kTableQuiet"], tables["kTableActive"]


def render(rows, bottom, step, quiet, active):
    out = [
        "// GENERATED by demo/tools/bake_atmosphere.py from source/physics/AtmosphereTable.cpp",
        "// -- do not edit by hand. demo/tools/check_shaders.py compares the two.",
        "//",
        "// NRLMSIS 2.1 (Emmert et al. 2021), Tromso 69.65 N 18.96 E, 2020-12-21 23:00 UT,",
        "// 80-800 km every 2 km, quiet (F10.7 70, Ap 4) and active (F10.7 230, Ap 30).",
        "// Five numbers a row: n(N2), n(O2), n(O) cm^-3, T K, mass density g cm^-3.",
        f"export const TABLE_ROWS = {rows};",
        f"export const TABLE_BOTTOM_KM = {bottom};",
        f"export const TABLE_STEP_KM = {step};",
    ]
    for name, table in (("QUIET", quiet), ("ACTIVE", active)):
        out.append(f"export const {name} = new Float64Array([")
        for fields in table:
            out.append("\t" + ", ".join(f.strip() for f in fields[:5]) + f",// {fields[5]} km")
        out.append("]);")
    return "\n".join(out) + "\n"


def main():
    with open(CPP) as handle:
        rows, bottom, step, quiet, active = parse(handle.read())
    if len(quiet) != rows or len(active) != rows:
        print(f"expected {rows} rows each, parsed {len(quiet)} quiet and {len(active)} active")
        return 1
    with open(OUT, "w") as handle:
        handle.write(render(rows, bottom, step, quiet, active))
    print(f"wrote {os.path.relpath(OUT, REPO)}: {rows} rows x 2 activity levels")
    return 0


if __name__ == "__main__":
    sys.exit(main())
