#!/usr/bin/env python3
"""Bake source/physics/AtmosphereTable.cpp from NRLMSIS 2.1 via pymsis
(pip install pymsis). Run once; the table is committed and nothing at build or
run time needs pymsis."""
import numpy as np, pymsis
alts = np.arange(80.0, 800.0+1e-9, 2.0)
date = np.datetime64('2020-12-21T23:00')
lat, lon = 69.65, 18.96
levels = [("quiet", 70.0, 70.0, 4.0), ("active", 230.0, 200.0, 30.0)]
V = pymsis.Variable
out = []
for name,f,fa,ap in levels:
    r = pymsis.calculate(date, lon, lat, alts, f107s=[f], f107as=[fa], aps=[[ap]*7], version=2.1)[0,0,0]
    out.append((name,f,fa,ap,r))
lines=[]
lines.append("// GENERATED by tools/bake_atmosphere.py -- do not edit by hand.")
lines.append("//")
lines.append("// NRLMSIS 2.1 (Emmert et al. 2021, doi:10.1029/2020EA001321), a US Naval")
lines.append("// Research Laboratory model, evaluated through pymsis %s. Tromso, 69.65 N" % pymsis.__version__)
lines.append("// 18.96 E, 2020-12-21 23:00 UT (local midnight, winter solstice), 80-800 km")
lines.append("// every 2 km. Two levels of activity:")
for name,f,fa,ap,_ in out:
    lines.append("//   %-7s F10.7 = %g, 81-day F10.7A = %g, Ap = %g" % (name,f,fa,ap))
lines.append("// Columns: n(N2), n(O2), n(O) in cm^-3; T in K; mass density in g cm^-3.")
lines.append('#include "physics/Atmosphere.h"')
lines.append("namespace boreal::atmosphere {")
lines.append("const int kTableRows = %d;" % len(alts))
lines.append("const double kTableBottomKm = %g;" % alts[0])
lines.append("const double kTableStepKm = %g;" % (alts[1]-alts[0]))
for idx,(name,f,fa,ap,r) in enumerate(out):
    lines.append("const Row kTable%s[] = {" % name.capitalize())
    for i,a in enumerate(alts):
        n2 = r[i,V.N2]*1e-6; o2=r[i,V.O2]*1e-6; o=r[i,V.O]*1e-6; T=r[i,V.TEMPERATURE]; rho=r[i,V.MASS_DENSITY]*1e-3
        lines.append("\t{ %.5e, %.5e, %.5e, %.2f, %.5e }, // %g km" % (n2,o2,o,T,rho,a))
    lines.append("};")
lines.append("} // namespace boreal::atmosphere")
open(__import__("pathlib").Path(__file__).resolve().parent.parent/"source/physics/AtmosphereTable.cpp","w").write("\n".join(lines)+"\n")
for name,f,fa,ap,r in out:
    for a in (100,110,150,200,250,300,400,500):
        i=int((a-80)/2)
        print(name,a, "N2 %.3e O2 %.3e O %.3e T %.0f"%(r[i,V.N2]*1e-6,r[i,V.O2]*1e-6,r[i,V.O]*1e-6,r[i,V.TEMPERATURE]))
